# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import eventex.subscriptions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20170622_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cpf',
            field=models.CharField(max_length=14, validators=[eventex.subscriptions.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
